branch-defaults:
  default:
    environment: front-env
    group_suffix: null
environment-defaults:
  front-env:
    branch: null
    repository: null
global:
  application_name: zatacka_frontend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
