# Generated by Django 2.2.1 on 2019-05-27 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
